CREATE TABLE DOMINO_GAME (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAYER_NAME VARCHAR2(50),
    WINNER VARCHAR2(50),
    SCORE NUMBER,
    GAME_DATE DATE DEFAULT SYSDATE
);

COMMIT;